In [11]:
#import tensorflow as tf

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [ ]:
import torch
from torch.utils.data import TensorDataset, random_split
from torch.utils.data import DataLoader, RandomSampler, SequentialSampler
from transformers import BertTokenizer, get_linear_schedule_with_warmup
from transformers import BertForSequenceClassification, AdamW, BertConfig
import torch.nn.functional as F


import pandas as pd
import numpy as np
import time
import datetime
import random, re
import seaborn as sns
import matplotlib.pyplot as plt

In [8]:
# Check device 
# Get the GPU device name if available.
if torch.cuda.is_available():    

    # Tell PyTorch to use the GPU.    
    device = torch.device("cuda")

    print('There are %d GPU(s) available. {}'.format(torch.cuda.device_count()))

    print('We will use the GPU: {}'.format(torch.cuda.get_device_name(0)))

# If we dont have GPU but a CPU, training will take place on CPU instead
else:
    print('No GPU available, using the CPU instead.')
    device = torch.device("cpu")
    
# Set the seed value all over the place to make this reproducible.
seed_val = 42

random.seed(seed_val)
np.random.seed(seed_val)
torch.manual_seed(seed_val)
torch.cuda.manual_seed_all(seed_val)
There are %d GPU(s) available. 1
We will use the GPU: Tesla P100-PCIE-16GB

SyntaxError: invalid syntax (Temp/ipykernel_6816/2159837497.py, line 24)

In [12]:
# Check device 
# Get the GPU device name if available.
if torch.cuda.is_available():    

    # Tell PyTorch to use the GPU.    
    device = torch.device("cuda")

    print('There are %d GPU(s) available. {}'.format(torch.cuda.device_count()))

    print('We will use the GPU: {}'.format(torch.cuda.get_device_name(0)))

# If we dont have GPU but a CPU, training will take place on CPU instead
else:
    print('No GPU available, using the CPU instead.')
    device = torch.device("cpu")
    
# Set the seed value all over the place to make this reproducible.
seed_val = 42

random.seed(seed_val)
np.random.seed(seed_val)
torch.manual_seed(seed_val)
torch.cuda.manual_seed_all(seed_val)
There are %d GPU(s) available. 1
We will use the GPU: Tesla P100-PCIE-16GB

SyntaxError: invalid syntax (Temp/ipykernel_6816/2159837497.py, line 24)

In [13]:
# Read the data
data = pd.read_csv('tweets.csv')
pd.set_option('display.max_colwidth', 150)
data.head()

,user,location,tweet,likes,RT,Source,ID,Date
0,AusNewsNetwork,Australia,"RT @AusHCVanuatu: Workplaces remain closed other than those providing essential services, as designated by the Vanuatu Government. \n\nStay hâ€¦",0,1,Twitter for iPhone,1502451057401556997,2022-03-12 01:07:00+00:00
1,citymb,"Manhattan Beach, CA 90266","COVID-19 Daily Update:\nMarch 11, 2022\nManhattan Beach New Cases: 4 (4,833 to date)\nManhattan Beach New Deaths: 0 (2â€¦ https://t.co/H6DTr8Sr9A",0,0,Twitter Web App,1502451053710622721,2022-03-12 01:07:00+00:00
2,TeleGeography,NaN,New intel allowed us to assess how COVID-19â€”paired with the OTT effect and trends among wholesale carriersâ€”have conâ€¦ https://t.co/RiWFuqvV0v,0,0,HubSpot,1502451053157040129,2022-03-12 01:06:59+00:00
3,biospace,"Des Moines, IA","The death toll related to COVID-19 is more than 6 million, according to the Johns Hopkins COVID-19 dashboard, but iâ€¦ https://t.co/8oIPwW17kE",0,0,HubSpot,1502451053136072707,2022-03-12 01:06:59+00:00
4,AnfieldWatch,United Kingdom,"ðŸš¨ NEW: Liverpool have some issues with COVID-19 amongst staff in the camp, and will wait until Saturday morning toâ€¦ https://t.co/iLxQRwji5M",0,0,Twitter Web App,1502451051546517505,2022-03-12 01:06:59+00:00